import React, { useState, useEffect, useContext } from 'react';
import { AuthContext } from '../context/AuthContext';
import { Shield, Search, Download, ChevronLeft, ChevronRight, FileText, Activity, Clock, Filter } from 'lucide-react';
import { API_BASE_URL } from '../config';
import { MotionCard, MotionButton } from '../components/motion';

const ITEMS_PER_PAGE = 5;

export default function SystemAuditLogs() {
  const { token, user } = useContext(AuthContext);
  const [logs, setLogs] = useState([]);
  const [searchQuery, setSearchQuery] = useState('');
  const [moduleFilter, setModuleFilter] = useState('ALL');
  const [currentPage, setCurrentPage] = useState(1);

  useEffect(() => {
    const fetchLogs = async () => {
      try {
        const res = await fetch(`${API_BASE_URL}/audit-logs?page=1&limit=50`, {
          headers: { Authorization: 'Bearer ' + token, 'Content-Type': 'application/json' }
        });
        const data = await res.json();
        if (res.ok && data.logs) {
          setLogs(data.logs);
        } else {
          setLogs([]);
        }
      } catch (e) {
        console.error(e);
        setLogs([]);
      }
    };
    if (token) fetchLogs();
  }, [token]);

  useEffect(() => {
    setCurrentPage(1);
  }, [searchQuery, moduleFilter]);

  const normalizedLogs = logs.map(l => ({
    id: l._id || l.id,
    timestamp: l.timestamp ? new Date(l.timestamp).toLocaleString('en-PH', { dateStyle: 'short', timeStyle: 'medium' }) : 'Recently',
    actor: (typeof l.actorUserId === 'object' ? l.actorUserId?.name : l.actor) || 'System Admin',
    role: l.actorRole || l.role || (typeof l.actorUserId === 'object' ? l.actorUserId?.role : 'Official'),
    module: l.targetModel || l.module || 'System',
    action: l.action || 'OPERATION',
    details: typeof l.details === 'object' ? JSON.stringify(l.details) : (l.details || 'Operation recorded'),
    status: l.status || (l.action?.includes('BLOCKED') ? 'BLOCKED' : 'SUCCESS'),
  }));

  const filteredLogs = normalizedLogs.filter(l => {
    const matchMod = moduleFilter === 'ALL' || l.module === moduleFilter;
    const q = searchQuery.toLowerCase().trim();
    const matchQuery = !q ||
      l.actor.toLowerCase().includes(q) ||
      l.role.toLowerCase().includes(q) ||
      l.module.toLowerCase().includes(q) ||
      l.action.toLowerCase().includes(q) ||
      l.details.toLowerCase().includes(q);
    return matchMod && matchQuery;
  });

  const totalPages = Math.ceil(filteredLogs.length / ITEMS_PER_PAGE) || 1;
  const startIndex = (currentPage - 1) * ITEMS_PER_PAGE;
  const currentItems = filteredLogs.slice(startIndex, startIndex + ITEMS_PER_PAGE);

  const handleDownloadPDF = () => {
    const printWin = window.open('', '_blank');
    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>MitigatePlus — Official System Audit Logs Report</title>
        <style>
          body { font-family: 'Plus Jakarta Sans', Arial, sans-serif; padding: 24px; color: #1A2332; }
          .header { border-bottom: 2px solid #173F56; padding-bottom: 12px; margin-bottom: 20px; }
          h1 { color: #173F56; margin: 0; font-size: 22px; }
          p { color: #6B7A8D; margin: 4px 0 0; font-size: 13px; }
          table { width: 100%; border-collapse: collapse; margin-top: 16px; }
          th, td { border: 1px solid #E2E7EE; padding: 8px 10px; font-size: 11px; text-align: left; }
          th { background: #173F56; color: #FFF; }
          .status { font-weight: bold; padding: 2px 6px; borderRadius: 4px; font-size: 10px; }
          .footer { margin-top: 30px; font-size: 11px; color: #6B7A8D; text-align: right; border-top: 1px solid #E2E7EE; padding-top: 10px; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>MitigatePlus — Official System Audit Logs Report</h1>
          <p>Lungsod ng Maynila • Generated by: ${user?.email || 'LGU SuperAdmin'} • Date: ${new Date().toLocaleString()}</p>
        </div>
        <table>
          <thead>
            <tr>
              <th>Timestamp</th>
              <th>Actor</th>
              <th>Role</th>
              <th>Module</th>
              <th>Action</th>
              <th>Details</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            ${filteredLogs.map(l => `
              <tr>
                <td>${l.timestamp}</td>
                <td>${l.actor}</td>
                <td>${l.role}</td>
                <td>${l.module}</td>
                <td><strong>${l.action}</strong></td>
                <td>${l.details}</td>
                <td><span class="status">${l.status}</span></td>
              </tr>
            `).join('')}
          </tbody>
        </table>
        <div class="footer">Certified System Audit Logs • Manila City MDRRMO Command Center</div>
      </body>
      </html>
    `;
    printWin.document.write(html);
    printWin.document.close();
    printWin.focus();
    setTimeout(() => printWin.print(), 500);
  };

  return (
    <div className="page-container page-animate">
      {/* ── Page Header ── */}
      <div className="workflow-header" style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 24, flexWrap: 'wrap', gap: 16 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 14 }}>
          <div style={{ width: 48, height: 48, borderRadius: 'var(--radius-inner)', background: 'linear-gradient(135deg, var(--manila-blue), #0e2a3a)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <Activity size={24} color="#fff" />
          </div>
          <div>
            <h1 className="section-header" style={{ margin: 0, fontSize: 22 }}>System Audit Logs</h1>
            <p style={{ fontSize: 13, color: 'var(--ink-soft)', marginTop: 2 }}>Real-time system-wide activity, security events, and operational audit trail across Manila City.</p>
          </div>
        </div>

        <button onClick={handleDownloadPDF} className="clay-button-secondary" style={{ padding: '8px 16px', fontSize: 13, gap: 8 }}>
          <Download size={15} /> Download PDF Audit Report
        </button>
      </div>

      {/* ── Search Bar & Filter Controls + Top Header Pagination ── */}
      <div className="clay-card" style={{ padding: 16, marginBottom: 20, display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 12 }}>
        <div style={{ position: 'relative', flex: 1, minWidth: 260 }}>
          <Search size={16} color="var(--ink-soft)" style={{ position: 'absolute', left: 12, top: '50%', transform: 'translateY(-50%)' }} />
          <input
            type="text"
            aria-label="Search logs by actor, action, module, or details"
            placeholder="Search logs by actor, action, module, or details..."
            value={searchQuery}
            onChange={e => setSearchQuery(e.target.value)}
            style={{ width: '100%', padding: '9px 12px 9px 36px', borderRadius: 'var(--radius-inner)', border: '1.5px solid var(--border)', fontSize: 13, outline: 'none', background: 'var(--card)', color: 'var(--ink)', boxSizing: 'border-box' }}
          />
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: 12, flexWrap: 'wrap' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <Filter size={15} color="var(--ink-soft)" />
            <select
              value={moduleFilter}
              aria-label="Filter by System Module"
              onChange={e => setModuleFilter(e.target.value)}
              style={{ padding: '8px 12px', borderRadius: 'var(--radius-inner)', border: '1.5px solid var(--border)', fontSize: 13, fontWeight: 700, color: 'var(--manila-blue)', background: 'var(--card)', outline: 'none', cursor: 'pointer' }}
            >
              <option value="ALL">All Modules</option>
              <option value="Relief Allocation Engine">Relief Allocation Engine</option>
              <option value="Field Staff Mobile App">Field Staff Mobile App</option>
              <option value="Special Relief Requests">Special Relief Requests</option>
              <option value="Warehouse Inventory">Warehouse Inventory</option>
              <option value="Distribution Events">Distribution Events</option>
              <option value="Account Management">Account Management</option>
              <option value="Fraud Interception">Fraud Interception</option>
            </select>
          </div>

          {/* TOP HEADER PAGINATION */}
          {totalPages > 1 && (
            <div style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
              <button
                onClick={() => setCurrentPage(p => Math.max(1, p - 1))}
                disabled={currentPage === 1}
                className="clay-button-secondary"
                style={{ padding: '5px 9px', fontSize: 11, opacity: currentPage === 1 ? 0.5 : 1 }}
              >
                <ChevronLeft size={13} />
              </button>
              {Array.from({ length: totalPages }, (_, i) => i + 1).map(page => (
                <button
                  key={page}
                  onClick={() => setCurrentPage(page)}
                  className={currentPage === page ? 'clay-button-primary' : 'clay-button-ghost'}
                  style={{ padding: 0, width: 26, height: 26, fontSize: 11, justifyContent: 'center' }}
                >
                  {page}
                </button>
              ))}
              <button
                onClick={() => setCurrentPage(p => Math.min(totalPages, p + 1))}
                disabled={currentPage === totalPages}
                className="clay-button-secondary"
                style={{ padding: '5px 9px', fontSize: 11, opacity: currentPage === totalPages ? 0.5 : 1 }}
              >
                <ChevronRight size={13} />
              </button>
            </div>
          )}
        </div>
      </div>

      {/* ── System Audit Table ── */}
      <div className="clay-card">
        <div className="table-container">
          <table className="clay-table">
            <thead>
              <tr>
                <th>Timestamp</th>
                <th>Actor / User</th>
                <th>Role</th>
                <th>System Module</th>
                <th>Action Code</th>
                <th>Audit Details</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              {currentItems.length === 0 ? (
                <tr>
                  <td colSpan="7" style={{ textAlign: 'center', padding: '36px', color: 'var(--ink-soft)' }}>
                    Walang nahanap na audit log para sa iyong hinahanap.
                  </td>
                </tr>
              ) : (
                currentItems.map(log => (
                  <tr key={log.id}>
                    <td style={{ fontSize: 12, color: 'var(--ink-soft)', whiteSpace: 'nowrap' }}>{log.timestamp}</td>
                    <td style={{ fontWeight: 700, color: 'var(--ink)', fontSize: 13 }}>{log.actor}</td>
                    <td>
                      <span style={{ fontSize: 11, fontWeight: 700, padding: '2px 8px', borderRadius: 999, background: log.role === 'LGU SuperAdmin' ? 'rgba(37,99,235,0.1)' : 'var(--sampaguita)', color: log.role === 'LGU SuperAdmin' ? 'var(--manila-blue)' : 'var(--ink)' }}>
                        {log.role}
                      </span>
                    </td>
                    <td style={{ fontSize: 12, fontWeight: 600, color: 'var(--ink)' }}>{log.module}</td>
                    <td>
                      <code style={{ fontSize: 11, background: 'var(--sampaguita)', padding: '2px 6px', borderRadius: 4, color: 'var(--manila-blue)', fontWeight: 800 }}>
                        {log.action}
                      </code>
                    </td>
                    <td style={{ fontSize: 12, color: 'var(--ink)', maxWidth: 300 }}>{log.details}</td>
                    <td>
                      <span className={`badge ${log.status === 'SUCCESS' ? 'badge-success' : log.status === 'BLOCKED' ? 'badge-danger' : 'badge-warning'}`} style={{ fontSize: 11 }}>
                        {log.status}
                      </span>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
